Org::Organ: &org
  factory/admin/organs: all
  factory/admin/taxons: all
  factory/admin/products: all
  factory/admin/productions: all
  factory/admin/taxon/products: all
  factory/agent/productions: all
Org::Member:
  <<: *org
